name: Node.js CI

on:
  push:
    branches: [ master, develop]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Initialize mandatory git config
      run: |
        git config user.name "GitHub Actions"
        git config user.email noreply@github.com
    - name: Push to release branch
      run: |
        echo ${GITHUB_REF#refs/heads/} >> test.txt
        git checkout -b release/${GITHUB_REF#refs/heads/}
        git add .
        git commit -m "Automated build frontend"
        git push origin release/${GITHUB_REF#refs/heads/}